= Besprechungsprotokoll 17.06.2021
Dumfarth, Starka
1.0, 17.06.2021: Some notes
ifndef::imagesdir[:imagesdir: ../images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
//icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-project/2021-da-chatbot/] ‏ ‏ ‎
icon:home[link=https://htl-leonding-project.github.io/2021-da-chatbot]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend

|Dumfarth Felix

|Starka Lukas

|Thomas Stütz

|

|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|Do. 17.06.2021, 19 - 19:40 Uhr
|Dauer
|40 Minuten
|===



== Besprochene Themen
Ein einfaches Verfahren für einen Chatbot implementieren

Konkreter

1.) Was wollen wir: Ein System, einen Chatbot, wo man die Antworten des Chatbots beurteilen kann und dieser dementsprechend dazu lernt

2.) Wie sehen Lerndaten aus?
Ein paar Zeilen in der Datenstruktur
Wie sieht man, was er dazugelernt hat? Kann man es überhaupt sehen?

Diese Fragen sollten bis zu den Ferien geklärt sein.

Vorgehensweise bei der Erstellung
1. Auswahlverfahren, welche Methode für die Vektorisierung gewählt werden soll
2. Anlegen von Testdaten
3. Ergebnis (ein paar Fragen) geben: Nur ein paar Testdaten um zu sehen, wie das ganze funktioniert => Wenn die Antworten besser werden ist dies ein Zeichen, dass es funktioniert
4. Dem Benutzer die Möglichkeit geben, dass diese Antworten bewertet werden => im Optimalfall soll dieser natürlich daraus lernen

Es soll nicht nur nach Keywords gesucht werden.

Wie?:
Fertiges Beispiel verwenden mit einem Framework
SpaCey oder mit Keras

Wir sollten vorhandenes Wissen anwenden und verstehen.

Jupyter als Anregung für ein Programm mit interaktiver Datenauswertung

== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann
| Schüler
a|
- Wie sehen die Lerndaten aus?
| Ferienbeginn
| Schüler
a|
- Prototyp beginnen
|

|===
