= Besprechungsprotokoll 11.05.2021
Dumfarth, Starka
1.0, 11.05.2021: Some notes
ifndef::imagesdir[:imagesdir: ../images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
//icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-project/2021-da-chatbot/] ‏ ‏ ‎
icon:home[link=https://htl-leonding-project.github.io/2021-da-chatbot]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend

|Dumfarth Felix

|Starka Lukas

|Thomas Stütz

|Christian Hammer

|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|Di. 11.05.2021, 18 - 18:56 Uhr
|Dauer
|56 min
|===



== Besprochene Themen
* Wir können auch ein halbfertiges Projekt nehmen, welches wir verändern und umbauen => müssen nicht bei 0 anfangen

* So schnell wie möglich mehr Theorie lernen (AI, Tokenization)

* Sobald wir unser mathematisches Model haben, können wir auch zwischen verschiedenen Technologien wechseln

== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann

| Schüler
a| - Präsentation des Ergebnisses der Bot-Recherche (der (mathematischen) Modelle dahinter).
 - Verwenden die verschiedenen ChatBot-Hersteller die selben ML-Verfahren oder verschiedene?
| 1. Juni 2021

| Alle
a| Wir verwenden YouTrack für die DA
| -

| Schüler
a| Bis zu den Ferien wissen, was wir wie machen müssen
| Anfang Ferien
|===
