= Besprechungsprotokoll 14.03.2022
Dumfarth, Starka
1.0, 14.03.2022: Some notes
ifndef::imagesdir[:imagesdir: ../images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
//icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-project/2021-da-chatbot/] ‏ ‏ ‎
icon:home[link=https://htl-leonding-project.github.io/2021-da-chatbot]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend

|Dumfarth Felix

|Starka Lukas

|Thomas Stütz

|


|===

.Ort und Zeit
[cols=2*]
|===
|Ort
| Schule
|von-bis
|Mo. 13.03.2022, 14:45 - 15:35  Uhr
|Dauer
| 50 Minuten
|===



== Besprochene Themen
Abkürzungen bei die ersten erwähnungen ausschreiben.

Chatbots am Beispiel Rasa: Text nicht aufbauend, etwas mehr erklären (vorerst lassen)

Confidence genauer erklären

Bei der TED Policy ... drei informationen als input ... : aufzählungspunkte und nicht nur Text
Pipline: phython-dict => erklärung.

Die Dinge erklären aber nicht in die mathematische tiefe.

Bei die Code Config snippets erklärung dazugeben

Keine füllwörter wie "leider auch", "sehr gut"!

Nach die Erklärungen beschreiben welche Configuration und weshalb wir benutzen.

Zuerst Backend und dann FrontEnd beschreiben.

Systemarchitektur

Conversation Statistiken vlt pro. Woche anzeigen

Diplomarbeit = vorliegende Arbeit

Was hat unser Dashboard für funktionalitäten, informationen darstellen, wie viele, wann, welche Conversationen geführt wurden.
Im dashboard sind alle Daten auch in rasa/rasa x vorhanden jedoch verteilt und versteckt => dashboard stellt diese einheitlich da, für den Leobot conversation (improvment) cycle

Kreis abbildung
Kreis beschreiben.

Regelkreis, in der literatur findet man den regel kreis, bsp heizung einer misst, einer regelt und schaut, temp anpassen wieder von vorne

Unseren regelkreis interpretieren wir so:
Konversationen mit user -> protokolierte conversationen -> intents ergänzt/ geändert/ gelöscht -> trainiert -> vorne

Regelkreis ist unser Dashboard
(sollwert = gelungene convo, istwert= falsche convo is blöd)
Men in the loop
An den Conversationen sieht man ob die änderungen gelungen sind, wo nicht muss ich mir anschauen wo schiefgelaufen

Beim Dashboard Unterhaltungen mit intents und entities anzeigen

Was have ich gemacht, was ist das Ziel,  warum monaco und nicht formular = weils flexibler ist.
um die flexibilität zu gewährleisten wurde bewusst auf formularfelder verzichtet stattdessen wird ein online editor (monaco) bearbeitet,
der user erhält eine unterstüzung mit autovervollständigung

nachteil vom editor = syntax muss user Beherrschen => deshalb Autovervollständigung

Dashboard wie amaturenbrett stellt nicht nur infos zur verfügung, gibt dem betreuer die möglichkeit zu verbessern.


== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann
|
Schüler
|
Diplomarbeit schreiben
|
-
|
Schüler
|
Dashboard erweitern
|
25.03.2022
|
Schüler
|
Project Award vorbereiten
|
25.03.2022
|===
