version: '3.7'

services:
  postgres:
    image: postgres
    container_name: microproject-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/:/var/lib/postgresql/data
    ports:
      - 5432:5432