@startuml
left to right direction
class Intent {
    - name: String
}
note right: name -> product-group

class IntentValue {
  - value: String
}
note right: value -> - Welche [Abteilungen] (ProductGroup) gibt es?\n               - Welche Fachrichtungen gibt es?

class Entity {
    - name: String
}
note right: Entity: Abteilung(wo sind die Synonyme?)

class EntityValue {
    - intentValue: IntentValue
    - entity: Entity
    - position: int
}
note right: Intent: Abteilung\n- Medientechnik\n- Informatik\n- Elektronik\n- Medizintechnik


class ExampleSentence {
    - id: Long
    - sentence: String
}


class Topic {
    - id: Long
    - name: String
}

class Response {
    - name: String
    - text: String
    - intent: Intent
}

class Slot {
    - name: String
    - value:
    - type: SlotType
    - influenceConversations: boolean
}
note right: zB Abteilung -> Medientechnik vom TYP STRING

class Synonym {

}

enum TopicType {
  FACHBEGRIFF,
  SMALLTALK
}

enum SlotType {
    TEXT,
    BOOL,
    CATEGORICAL,
    FLOAT,
    LIST,
    ANY
}

Slot -> SlotType
Topic -right> TopicType
IntentValue "*" -right> "1" Intent : consists of <
Response "*" -left> "1" Intent : has <
EntityValue "*" -right> "1" IntentValue
EntityValue "*" -left> "1" Entity
@enduml


